version: '3.5'
services:
    php:
        build: ./docker/php-fpm
        container_name: test_php
        volumes:
            - ./:/var/www:cached
            - ./logs/symfony:/var/www/var/log:cached
        links:
            - mysql
        networks:
            - test_symfony

    nginx:
        build: ./docker/nginx
        container_name: test_nginx
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./:/var/www:cached
            - ./docker/nginx/test.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        links:
            - php
        networks:
            - test_symfony

    mysql:
        image: mysql:5.6
        container_name: test_mysql
        volumes:
            - ./docker/db:/var/lib/mysql
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: test
            MYSQL_USER: test_user
            MYSQL_PASSWORD: 123456
        networks:
            - test_symfony

networks:
    test_symfony:
        name: test_symfony
